- name: demo on vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{ URL }}
    - name: print variable on task
      vars:
      URL : task.exampke.com
      debug:
        msg: URL = {{URL}}




