- name: demo on vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{ URL }}
    - name: Print variable from task
      vars:
       URL: task.example.com
      debug:
          msg: URL = {{ URL }}

- name: demo on variable from file
    hosts: all
      vars_file:
        - example-vars.yml

        vars:

        debug:
          msg: URL = {{ URL }}




